/**
 * Server-authoritative price catalog for physical print products.
 * All prices in pence (GBP).
 *
 * Rebuilt from the live onjjem.com product catalog to guarantee Stripe
 * checkout always charges exactly what the website displays. Previously
 * this file held a stale, unrelated product set (Christmas items, photo
 * books, etc.) that caused customers to be charged old/wrong prices —
 * e.g. Magic Mug displayed at £17.99 but Stripe charged only £13.99.
 */

export interface CatalogEntry {
  name: string;
  pricePence: number;
}

export const SHOP_SKU_PRICES: Record<string, CatalogEntry> = {
  "canvas-stretched-a5": { name: 'Stretched Canvas (A5)', pricePence: 2849 },
  "canvas-stretched-a4": { name: 'Stretched Canvas (A4)', pricePence: 3999 },
  "canvas-stretched-a3": { name: 'Stretched Canvas (A3)', pricePence: 4599 },
  "canvas-stretched-a2": { name: 'Stretched Canvas (A2)', pricePence: 6499 },
  "canvas-stretched-a1": { name: 'Stretched Canvas (A1)', pricePence: 8999 },
  "canvas-stretched-a0": { name: 'Stretched Canvas (A0)', pricePence: 12499 },
  "eco-canvas-8x12": { name: 'Eco Canvas (8x12 inch)', pricePence: 2899 },
  "eco-canvas-12x12": { name: 'Eco Canvas (12x12 inch)', pricePence: 3099 },
  "eco-canvas-12x18": { name: 'Eco Canvas (12x18 inch)', pricePence: 3299 },
  "eco-canvas-16x16": { name: 'Eco Canvas (16x16 inch)', pricePence: 3999 },
  "eco-canvas-16x24": { name: 'Eco Canvas (16x24 inch)', pricePence: 4499 },
  "eco-canvas-20x20": { name: 'Eco Canvas (20x20 inch)', pricePence: 4499 },
  "eco-canvas-20x30": { name: 'Eco Canvas (20x30 inch)', pricePence: 4899 },
  "slim-canvas-6x6": { name: 'Slim Canvas (6x6 inch)', pricePence: 2499 },
  "slim-canvas-12x12": { name: 'Slim Canvas (12x12 inch)', pricePence: 3999 },
  "slim-canvas-30x30": { name: 'Slim Canvas (30x30 inch)', pricePence: 9699 },
  "slim-canvas-43x87": { name: 'Slim Canvas (43x87 inch)', pricePence: 21999 },
  "eco-rolled-10x10": { name: 'Eco Rolled Canvas (10x10 inch)', pricePence: 2499 },
  "eco-rolled-10x12": { name: 'Eco Rolled Canvas (10x12 inch)', pricePence: 2499 },
  "eco-rolled-11x14": { name: 'Eco Rolled Canvas (11x14 inch)', pricePence: 2699 },
  "eco-rolled-12x12": { name: 'Eco Rolled Canvas (12x12 inch)', pricePence: 2699 },
  "eco-rolled-12x16": { name: 'Eco Rolled Canvas (12x16 inch)', pricePence: 2999 },
  "eco-rolled-12x18": { name: 'Eco Rolled Canvas (12x18 inch)', pricePence: 2999 },
  "eco-rolled-10x20": { name: 'Eco Rolled Canvas (10x20 inch)', pricePence: 3499 },
  "eco-rolled-12x24": { name: 'Eco Rolled Canvas (12x24 inch)', pricePence: 3499 },
  "eco-rolled-16x20": { name: 'Eco Rolled Canvas (16x20 inch)', pricePence: 3999 },
  "eco-rolled-20x20": { name: 'Eco Rolled Canvas (20x20 inch)', pricePence: 3999 },
  "eco-rolled-24x47": { name: 'Eco Rolled Canvas (24x47 inch)', pricePence: 4499 },
  "eco-rolled-28x40": { name: 'Eco Rolled Canvas (28x40 inch)', pricePence: 4499 },
  "art-print-5x7": { name: 'Museum-Grade Fine Art Print (5x7 inch)', pricePence: 999 },
  "art-print-8x10": { name: 'Museum-Grade Fine Art Print (8x10 inch)', pricePence: 1299 },
  "art-print-11x14": { name: 'Museum-Grade Fine Art Print (11x14 inch)', pricePence: 1799 },
  "art-print-12x16": { name: 'Museum-Grade Fine Art Print (12x16 inch)', pricePence: 1999 },
  "art-print-24x32": { name: 'Museum-Grade Fine Art Print (24x32 inch)', pricePence: 3299 },
  "art-print-36x48": { name: 'Museum-Grade Fine Art Print (36x48 inch)', pricePence: 5799 },
  "art-foil-a4-gold": { name: 'Premium Metallic Foil Art Print (A4 / Gold)', pricePence: 2599 },
  "art-foil-a4-silver": { name: 'Premium Metallic Foil Art Print (A4 / Silver)', pricePence: 2599 },
  "art-foil-a3-gold": { name: 'Premium Metallic Foil Art Print (A3 / Gold)', pricePence: 2899 },
  "art-foil-a3-silver": { name: 'Premium Metallic Foil Art Print (A3 / Silver)', pricePence: 2899 },
  "art-foil-a2-gold": { name: 'Premium Metallic Foil Art Print (A2 / Gold)', pricePence: 3499 },
  "art-foil-a2-silver": { name: 'Premium Metallic Foil Art Print (A2 / Silver)', pricePence: 3499 },
  "art-foil-a1-gold": { name: 'Premium Metallic Foil Art Print (A1 / Gold)', pricePence: 4499 },
  "art-foil-a1-silver": { name: 'Premium Metallic Foil Art Print (A1 / Silver)', pricePence: 4499 },
  "art-gitd-premium-a1": { name: 'Glow in the Dark Poster (A1)', pricePence: 4499 },
  "art-gitd-premium-a2": { name: 'Glow in the Dark Poster (A2)', pricePence: 3199 },
  "art-gitd-premium-a3": { name: 'Glow in the Dark Poster (A3)', pricePence: 2499 },
  "art-gitd-premium-a4": { name: 'Glow in the Dark Poster (A4)', pricePence: 1999 },
  "photo-tile-5x7": { name: 'Framed Photo Tiles (5x7 inch)', pricePence: 1799 },
  "photo-tile-8x8": { name: 'Framed Photo Tiles (8x8 inch)', pricePence: 2099 },
  "photo-tile-8x10": { name: 'Framed Photo Tiles (8x10 inch)', pricePence: 2199 },
  "magic-mug": { name: 'ChromaCoat Mug (11oz Heat-Activated Mug)', pricePence: 1799 },
  "mug-11oz": { name: 'Photo Mugs (11oz Mug)', pricePence: 1199 },
  "mug-15oz": { name: 'Photo Mugs (15oz Large Mug)', pricePence: 2099 },
  "coaster-2pk": { name: 'Custom Wooden Drink Coasters (Set of 2)', pricePence: 1199 },
  "coaster-4pk": { name: 'Custom Wooden Drink Coasters (Set of 4)', pricePence: 1699 },
  "tea-towel-poly": { name: 'Premium Personalised Kitchen Towel (Polyester)', pricePence: 1499 },
  "tea-towel-cotton": { name: 'Premium Personalised Kitchen Towel (Cotton Twill)', pricePence: 1899 },
  "magnet-fridge-3x2": { name: 'Photo Magnets (Fridge Magnet 3x2)', pricePence: 899 },
  "magnet-fridge-6x4": { name: 'Photo Magnets (Fridge Magnet 6x4)', pricePence: 999 },
  "magnet-acrylic-2x3": { name: 'Photo Magnets (Acrylic Magnet 2x3)', pricePence: 1299 },
  "magnet-square-4x4": { name: 'Photo Magnets (Square Magnet 4x4)', pricePence: 1199 },
  "magnet-square-6x6": { name: 'Photo Magnets (Square Magnet 6x6)', pricePence: 1799 },
  "jigsaw-30": { name: 'Photo Jigsaw (30 pieces (Pocket Masterpiece))', pricePence: 2499 },
  "jigsaw-110": { name: 'Photo Jigsaw (110 pieces (The Perfect Gift))', pricePence: 2799 },
  "jigsaw-252": { name: 'Photo Jigsaw (252 pieces (The Rainy Day Choice))', pricePence: 2999 },
  "jigsaw-500": { name: 'Photo Jigsaw (500 pieces (The Weekend Challenge))', pricePence: 3499 },
  "jigsaw-1000": { name: 'Photo Jigsaw (1000 pieces (The Ultimate Puzzle))', pricePence: 3799 },
  "playing-cards": { name: 'Personalised Photo Playing Cards (Full Deck)', pricePence: 1799 },
  "budget-poster-a5-portrait": { name: 'Budget Poster (A5 / Portrait)', pricePence: 1899 },
  "budget-poster-a5-landscape": { name: 'Budget Poster (A5 / Landscape)', pricePence: 1899 },
  "budget-poster-a4-portrait": { name: 'Budget Poster (A4 / Portrait)', pricePence: 1899 },
  "budget-poster-a4-landscape": { name: 'Budget Poster (A4 / Landscape)', pricePence: 1899 },
  "budget-poster-a3-portrait": { name: 'Budget Poster (A3 / Portrait)', pricePence: 1999 },
  "budget-poster-a3-landscape": { name: 'Budget Poster (A3 / Landscape)', pricePence: 1999 },
  "budget-poster-a2-portrait": { name: 'Budget Poster (A2 / Portrait)', pricePence: 2199 },
  "budget-poster-a2-landscape": { name: 'Budget Poster (A2 / Landscape)', pricePence: 2199 },
  "budget-poster-a1-portrait": { name: 'Budget Poster (A1 / Portrait)', pricePence: 2499 },
  "budget-poster-a1-landscape": { name: 'Budget Poster (A1 / Landscape)', pricePence: 2499 },
  "budget-poster-a0-portrait": { name: 'Budget Poster (A0 / Portrait)', pricePence: 2799 },
  "budget-poster-a0-landscape": { name: 'Budget Poster (A0 / Landscape)', pricePence: 2799 },
  "exoboard-200x300": { name: 'Rigid Display Board (8x12 inch (200x300mm))', pricePence: 3599 },
  "exoboard-210x297": { name: 'Rigid Display Board (8x12 inch (210x297mm))', pricePence: 3599 },
  "exoboard-297x420": { name: 'Rigid Display Board (12x17 inch)', pricePence: 4099 },
  "exoboard-300x400": { name: 'Rigid Display Board (12x16 inch)', pricePence: 4299 },
  "exoboard-400x500": { name: 'Rigid Display Board (16x20 inch)', pricePence: 5099 },
  "exoboard-450x600": { name: 'Rigid Display Board (18x24 inch)', pricePence: 5899 },
  "exoboard-594x841": { name: 'Rigid Display Board (23x33 inch)', pricePence: 7099 },
  "exoboard-600x800": { name: 'Rigid Display Board (24x31 inch)', pricePence: 7599 },
  "exoboard-700x1000": { name: 'Rigid Display Board (28x39 inch)', pricePence: 9599 },
  "exoboard-841x1189": { name: 'Rigid Display Board (33x47 inch)', pricePence: 11599 },
  "pet-tag-round": { name: 'Pet Tags (Round Tag)', pricePence: 1399 },
  "pet-tag-bone": { name: 'Pet Tags (Bone Shape Tag)', pricePence: 1399 },
  "tattoo-s": { name: 'Temporary Tattoos (Small (5cm x 7.5cm))', pricePence: 1199 },
  "tattoo-m": { name: 'Temporary Tattoos (Medium (7.5cm x 10cm))', pricePence: 1499 },
  "tattoo-l": { name: 'Temporary Tattoos (Large (10cm x 15cm))', pricePence: 1799 },
  "tattoo-xl": { name: 'Temporary Tattoos (Extra Large (20cm x 20cm))', pricePence: 2099 },
  "tattoo-xxl": { name: 'Temporary Tattoos (XXL (30cm x 30cm))', pricePence: 2899 },
  "budget-art-paper-8x8": { name: 'Budget Art Paper (8x8 inch)', pricePence: 1299 },
  "budget-art-paper-12x16": { name: 'Budget Art Paper (12x16 inch)', pricePence: 1799 },
  "budget-art-paper-18x24": { name: 'Budget Art Paper (18x24 inch)', pricePence: 2499 },
  "budget-art-paper-40x40": { name: 'Budget Art Paper (40x40 inch)', pricePence: 3499 },
  "printed-towel-shower": { name: 'Printed Shower Towel (70x140cm)', pricePence: 3499 },
  "water-bottle-copper-grey": { name: 'Personalised Insulated Water Bottle (Grey)', pricePence: 2999 },
  "water-bottle-copper-navy": { name: 'Personalised Insulated Water Bottle (Navy)', pricePence: 2999 },
  "water-bottle-copper-red": { name: 'Personalised Insulated Water Bottle (Red)', pricePence: 2999 },
  "water-bottle-copper-lime": { name: 'Personalised Insulated Water Bottle (Lime)', pricePence: 2999 },
  "photo-print-5x5": { name: '5x5 Inch Personalised Photo Print (Unframed)', pricePence: 699 },
};
